apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rsweb1

spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
      dc: IN
      app: webserver
  template:
    metadata:
      name: mypod1
      labels:
        dc: IN
        env: prod
        app: webserver
    spec:
      containers:
      - name: "mycon1"
        image: "vimal13/apache-webserver-php"